### ISSUE TITLE
Bug: UnityConverterInitializer registers too many converters

### ISSUE THREAD

**Issue by rumcgit** [jilleJr/Newtonsoft.Json-for-Unity.Converters#36]
## Description
`JsonConvert.SerializeObject()` converts integers to strings, if we pass JToken !

## Example
```
var str = "{\"a\":123}";
var jtoken = JsonConvert.DeserializeObject<JToken>(str);
var badSerializedString = JsonConvert.SerializeObject(jtoken);
var goodSerializedString = jtoken.ToString(Formatting.None);
Debug.Log(badSerializedString);  // outputs: {"a":"123"}
Debug.Log(goodSerializedString); // outputs: {"a":123}
```
## Expected behavior
badSerializedString should be just the same as goodSerializedString: `{"a": 123}`

## Versions
Newtnosoft.Json-for-Unity version: 12.0 (latest)
Unity version: 2019.1.14f1
Platforms affected: android, ios, webgl, editor

**Comment by jilleJr** [comment]
@rumcgit There is a new preview out with an editor to enable/disable any given converter. Try it out already by updating to version `1.1.0-preview.2`, then access the settings via "Edit > Json .NET converters settings..."

![image](https://user-images.githubusercontent.com/2477952/87709223-3a9aaa00-c7a4-11ea-93bb-9313c32cf239.png)

and then disabling your converter from the global default converters settings.

Example:

![GIF 2020-07-16 20-37-31](https://user-images.githubusercontent.com/2477952/87709233-3ec6c780-c7a4-11ea-80d8-922732927d8d.gif)

Don't fray to reopen or create new issues if you have more troubles. :)

**Comment by mastef** [comment]
@applejag I also just stumbled across this. Newtonsoft was crashing the editor due to serialization of the Color element, so I was lucky I stumbled across your package.

But then a custom converter we have for a specific type ( only attached through JsonConverter attribute ) was suddenly throwing errors, since it didn't have a `CanConvert` method implementation. Even more curiously it happened during "unity.service.core" requests that the editor was sending.

What's the expected default behavior here normally that requires this package to work correctly?

It seems weird that external converters are automatically attached. The default behavior would be to just include the Unity Converters from this repo - the Newtonsoft.Json converters are normally also not included unless specified in the options, right? Or are the VersionConverter and StringEnumConverter required for this package to work?

**Comment by applejag** [comment]
@mastef Hello! The original reason for this is because I wanted this project to be a follow-up on Wanzyee's package: http://wanzyeestudio.blogspot.com/2017/03/jsonnet-converters.html

When creating this package originally, I got permission from Wanzyee to base my work off of his.

So to make this project only be an extension of that package, I adopted this behavior from his package.

I agree now that it might not have been the wisest decision. However, changing this is a breaking change. And now that this package has gained some traction, it's even harder to revert this decision.

I'm no longer using Unity anymore (not even in hobby projects), so I'm not having any will to put any effort into this project anymore. I'm only spending minimal effort into it. The only reason I haven't archived this repo is to allow people to submit issues about critical bugs if there are any, or to allow other to submit PRs.
